@startuml
skinparam monochrome true
actor 商户
participant "饭好约管理后台" as A
participant "presell-pay" as B
participant "银准" as C
participant "DB层" as D
商户 -> A: 1.发起提现请求，输入提现金额
activate A
A -> B: 2.根据商户输入的提现金额发起提现申请
activate B
B -> C: 3.查询子商户账号信息以及余额
activate C
C --> B: 4.返回子商户信息以及余额
deactivate C
B --> B: 5.判断商户余额是否充足
B --> A: 6.余额不足
A --> 商户: 7.余额不足
B -> C: 8.余额充足，向银准发送提现申请，并传入回调 url
activate C
C --> C: 商户提现操作（应该是像银行发起提现）
C --> B: 9.返回提现结果（这里并不是银行返回的结果）
deactivate C
B --> D: 10.记录商户提现流水，同时记录商户提现状态
activate D
deactivate D
B --> A: 11.提现正在处理
A --> 商户: 12.提现正在受理
deactivate A
B --> C: 13.每隔 5 分钟查询提现状态
activate C
C --> B: 14.返回提现状态
deactivate C
B --> D: 15.如果提现状态为成功则修改提现流水的状态
deactivate B
@enduml