@startuml
skinparam monochrome true
actor 运营 
participant "商家管理后台" as A
participant "presell-pay" as B
participant "银准" as C
participant "DB层" as D
运营 -> A: 1.进入管理后台
activate A
A -> B: 2.输入银行卡号解绑银行卡
activate B
B -> C: 3.发送子商户账号和银行卡号，调用解绑接口
activate C
C --> C: 解绑商户的卡号
C --> B: 5.返回解绑成功的数据
deactivate C
B --> D: 6.修改我们数据库维护的信息，将商户和卡号设置为解绑状态
B --> D: 7.记录商户解绑操作记录
B --> A: 8.解绑成功
deactivate B
A --> 运营: 展示结果
deactivate A
@enduml